x-uffizzi:
  ingress:
    service: app
    port: 3000
    
services:
  app:
    build: .
    ports:
      - "3000:3000"
license: FT7YCAYBAEDUY2LDMVXHGZIB76BAAAIDAECEIYLUMEAQUAABAFJAD74EAAAQCUYB76CAAAAABL7YGBIBAL7YMAAAAD77H74CAH7YO6ZCOZSXE43JN5XCEORSFQRGK3LBNFWCEORCORRWM2DWM5WWE3TCIB3GS5TBNRSGSLTOMV2CELBCMNXW24DBNZ4SEORCKRSWC3JAKVXG6IRMEJZWKYLUOMRDUNJMEJ2GSZLSEI5CE43DMFWGKIRMEJ2HE2LBNQRDUZTBNRZWKLBCMVXGIIR2EIZDAMRUFUYTELJTGFKDAMB2GAYDUMBQLIRH2AJRAJ2IUJKLKRKHEQQVZXEBAFSKFQWPBIJNC6RDI6IG42UMNGCN5DMVWO5XCZFS53IT4MA3UQWJBYN5VGIBGEBPYXHQ4VRVIRNYXOZCSPN63HFRYNFTR5JS4Y4QFVCOIB56HU6GIH636R7LS6NTTGGFGGT6KO6FW6IYAA======
